<../../../mkconfig

TARG=\
	mkext.dis\
	mkfs.dis\
	mkrm.dis\
	part.dis\
	kfscmd.dis\
	kfswiz.dis\
	format.dis\
	ftl.dis\

SYSMODULES=\
	arg.m\
	sys.m\
	draw.m\
	bufio.m\
	string.m\

DISBIN=$ROOT/dis/disk

<$ROOT/mkfiles/mkdis
